In [2]:
import numpy as np
import gym
import random
import time
from  IPython.display import clear_output

In [3]:
env = gym.make('FrozenLake-v0')

In [4]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size , action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
num_episodes = 10000
max_steps_per_epi = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_explo_rate = 1
min_explo_rate = 0.01

exploration_decay_rate = 0.01

In [14]:
rewards_all_episodes = []

for episode in range(num_episodes):

  state = env.reset()
  done = False
  rewards_current_episode = 0

  for step in range(max_steps_per_epi):

    exploration_rate_threshold = random.uniform(0,1)
    if exploration_rate_threshold > exploration_rate:
      action = np.argmax(q_table[state,:])

    else:
      action = env.action_space.sample()

    new_state , reward , done , info = env.step(action)

    q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
        learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

    state = new_state
    rewards_current_episode += reward

    if done == True:
      break

  exploration_rate = min_explo_rate + \
      (max_explo_rate - min_explo_rate) * np.exp(-exploration_decay_rate*episode)

  rewards_all_episodes.append(rewards_current_episode)

rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

print("\n\n********Q-table********\n")
print(q_table)

********Average reward per thousand episodes********

1000 :  0.5060000000000003
2000 :  0.6970000000000005
3000 :  0.6890000000000005
4000 :  0.7000000000000005
5000 :  0.6910000000000005
6000 :  0.6850000000000005
7000 :  0.6450000000000005
8000 :  0.6950000000000005
9000 :  0.6670000000000005
10000 :  0.7020000000000005


********Q-table********

[[0.52591199 0.50734046 0.49638525 0.47983868]
 [0.30680368 0.37463015 0.35955886 0.49004433]
 [0.42774685 0.42439239 0.41891208 0.45501404]
 [0.30568446 0.33274115 0.34008461 0.43025516]
 [0.54231324 0.39008193 0.42728569 0.42582758]
 [0.         0.         0.         0.        ]
 [0.15651571 0.10151391 0.32158181 0.1496628 ]
 [0.         0.         0.         0.        ]
 [0.31511916 0.31163976 0.4032984  0.56848268]
 [0.4690699  0.60918639 0.51083798 0.33293365]
 [0.57061443 0.44270894 0.42570508 0.28309008]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.43487565 0.65160332 0.67627809 0.

In [16]:
for episode in range(3):

  state = env.reset()
  done = False
  print("********Episode ",episode + 1 , "**********\n\n\n")
  time.sleep(1)

  for step in range(max_steps_per_epi):
    clear_output(wait = True)
    env.render()
    time.sleep(0.3)

    action = np.argmax(q_table[state,:])
    new_state, reward, done , info = env.step(action)

    if done:
      clear_output(wait = True)
      env.render()
      if reward == 1:
        print("****You Have Reached The Goal!!*****")
        time.sleep(3)

      else:
        print("****You Have Fallen Into Hole****")
        time.sleep(3)

      clear_output(wait = True)
      break

    state = new_state

env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You Have Reached The Goal!!*****
